# Generated by Django 5.2.4 on 2025-08-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finsideapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='varietyd',
            name='image',
            field=models.ImageField(default=1, upload_to='cars/'),
            preserve_default=False,
        ),
    ]
