# Generated by Django 5.2.4 on 2025-08-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finsideapp', '0002_varietyd_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='varietyd',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
