# Generated by Django 5.2.4 on 2025-08-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finsideapp', '0003_varietyd_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='varietyd',
            name='price',
            field=models.TextField(default=0),
        ),
    ]
